name: Kamal Deployment
on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Ruby and Gems
      uses: ruby/setup-ruby@v3
      with:
        bundler-cache: true

    - name: Install Kamal
      run: gem install kamal

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        echo "RAILS_MASTER_KEY=$RAILS_MASTER_KEY" >> .env
        echo "KAMAL_REGISTRY_PASSWORD=$KAMAL_REGISTRY_PASSWORD" >> .env
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan 15.206.125.202 >> ~/.ssh/known_hosts || echo "Failed to add host"
        ssh-keyscan 3.110.49.102 >> ~/.ssh/known_hosts || echo "Failed to add host"

      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
        KAMAL_REGISTRY_PASSWORD: ${{ secrets.KAMAL_REGISTRY_PASSWORD }}
        SECRET_KEY_BASE: ${{secrets.SECRET_KEY_BASE}}

    - name: Kamal Deploy
      run: kamal deploy
