name: Deploy to Kamal

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        IMAGE_TAG=${{ github.sha }}   # Tagging the image with the commit SHA
        docker buildx build --platform linux/amd64 \
          --tag pratikingle09/kamal_project_rails:$IMAGE_TAG \
          --tag pratikingle09/kamal_project_rails:latest \
          --push .   # The `--push` flag ensures the image is pushed to Docker Hub
          
    - name: Install Kamal
      run: gem install kamal

    - name: Deploy to Kamal
      run: |
        kamal deploy \
          --image pratikingle09/kamal_project_rails:${{ github.sha }}
      continue-on-error: false

    - name: Rollback if deployment fails
      if: ${{ failure() }}
      run: |
        kamal rollback
